import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type {
  Client,
  ClientWithCounts,
  CreateClientInput,
  UpdateClientInput,
  ListClientsParams,
  PaginatedClients
} from '@/lib/types/client';

/**
 * Create Supabase admin client with service role key
 * This bypasses RLS policies - only use on server side
 */
function createSupabaseAdmin(): SupabaseClient {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !serviceRoleKey) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  }

  return createClient(url, serviceRoleKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  });
}

/**
 * ClientService handles all client-related database operations
 *
 * Features:
 * - CRUD operations for client records
 * - Cursor-based pagination for efficient list queries
 * - Full-text search across client fields
 * - Tag-based filtering
 * - Soft delete with RLS policy enforcement
 *
 * Uses Supabase for data persistence with Row Level Security (RLS) policies
 * ensuring users can only access their own clients.
 *
 * @example
 * ```typescript
 * const clientService = new ClientService();
 *
 * // Create a new client
 * const client = await clientService.createClient({
 *   name: "John Doe",
 *   email: "john@example.com"
 * });
 *
 * // List clients with pagination
 * const result = await clientService.listClients({ limit: 20 });
 * ```
 */
export class ClientService {
  private supabase: SupabaseClient;

  /**
   * Initialize ClientService with admin Supabase client
   * Uses service role key to bypass RLS - only use on server side
   *
   * @throws {Error} If Supabase credentials are not configured
   */
  constructor() {
    this.supabase = createSupabaseAdmin();
  }

  /**
   * Create a new client
   *
   * @param data - Client data to create
   * @param userId - The authenticated user's ID (required, from Better Auth session)
   * @returns Promise<Client> The created client record
   * @throws {Error} If user ID is not provided
   * @throws {Error} If email or phone already exists
   * @throws {Error} If database operation fails
   *
   * @example
   * ```typescript
   * const client = await clientService.createClient({
   *   name: "John Doe",
   *   email: "john@example.com",
   *   phone: "+1-555-123-4567"
   * }, userId);
   * ```
   */
  async createClient(data: CreateClientInput, userId: string): Promise<Client> {
    if (!userId) {
      throw new Error('User ID is required');
    }

    // Extract tags from data (they're not part of the clients table)
    const { tags, ...clientData } = data;

    // Insert client into database (UUID auto-generated by PostgreSQL)
    const { data: client, error } = await this.supabase
      .from('clients')
      .insert({
        ...clientData,
        created_by: userId,
        assigned_to: userId,
        is_deleted: false,
      })
      .select()
      .single();

    if (error) {
      // Check for unique constraint violation (duplicate email/phone)
      if (error.code === '23505') {
        throw new Error('Email or phone already exists');
      }
      throw new Error(error.message);
    }

    // Add tags if provided
    if (tags && tags.length > 0 && client) {
      const tagRecords = tags.map((tagName: string) => ({
        client_id: client.id,
        tag_name: tagName,
        created_by: userId,
      }));

      const { error: tagError } = await this.supabase
        .from('client_tags')
        .insert(tagRecords);

      if (tagError) {
        // Log error but don't fail the request (tags are optional)
        console.error('Failed to add tags:', tagError);
      }
    }

    return client;
  }

  /**
   * List clients with pagination, search, and filtering
   *
   * Supports cursor-based pagination for efficient browsing of large datasets.
   * Results are filtered by user ownership and exclude soft-deleted clients.
   *
   * @param params - Query parameters for filtering and pagination
   * @param userId - The authenticated user's ID (required for authorization)
   * @returns Promise<PaginatedClients> Paginated client list with total count and next cursor
   * @throws {Error} If database query fails
   */
  async listClients(params: ListClientsParams, userId: string): Promise<PaginatedClients> {
    if (!userId) {
      throw new Error('User ID is required');
    }

    // Validate and enforce limit: default 20, max 100
    const limit = Math.min(Math.max(params.limit || 20, 1), 100);

    // Build select statement - use inner join when filtering by tag
    // The !inner modifier creates INNER JOIN instead of LEFT JOIN,
    // ensuring only clients with matching tags are returned
    const selectStatement = params.tag
      ? '*, client_tags!inner(tag_name)'
      : '*, client_tags(tag_name)';

    // Build query with count for pagination
    // Filter by user ownership (assigned_to)
    let query = this.supabase
      .from('clients')
      .select(selectStatement, { count: 'exact' })
      .eq('assigned_to', userId)
      .eq('is_deleted', false)
      .order(params.sort || 'created_at', { ascending: false });

    // Cursor-based pagination using created_at
    if (params.cursor) {
      query = query.lt('created_at', params.cursor);
    }

    // Search by name or email (case-insensitive)
    if (params.search) {
      query = query.or(`name.ilike.%${params.search}%,email.ilike.%${params.search}%`);
    }

    // Filter by tag using related table filter
    if (params.tag) {
      query = query.eq('client_tags.tag_name', params.tag);
    }

    // Filter by status
    if (params.status) {
      query = query.eq('status_id', params.status);
    }

    // Apply limit last
    query = query.limit(limit);

    // Execute query
    const { data, error, count } = await query;

    if (error) {
      throw new Error(`Failed to list clients: ${error.message}`);
    }

    // Calculate next cursor from last item's created_at
    const next_cursor = data && data.length === limit
      ? data[data.length - 1].created_at
      : undefined;

    return {
      data: data || [],
      next_cursor,
      total_count: count || 0,
    };
  }

  /**
   * Get client by ID with related data counts
   *
   * Retrieves a single client record with aggregated counts of related data.
   * Verifies user ownership before returning data.
   *
   * @param id - The client ID to retrieve
   * @param userId - The authenticated user's ID (required for authorization)
   * @returns Promise<ClientWithCounts | null> The client with related counts, or null if not found
   * @throws {Error} If database query fails
   */
  async getClientById(id: string, userId: string): Promise<ClientWithCounts | null> {
    if (!userId) {
      throw new Error('User ID is required');
    }

    const { data: client, error } = await this.supabase
      .from('clients')
      .select(`
        *,
        documents:client_documents(count),
        notes:client_notes(count),
        tasks:client_tasks(count),
        tags:client_tags(tag_name)
      `)
      .eq('id', id)
      .eq('assigned_to', userId)
      .eq('is_deleted', false)
      .single();

    if (error) {
      // PGRST116 is PostgREST's "row not found" error
      if (error.code === 'PGRST116') {
        return null;
      }
      throw new Error(error.message);
    }

    // Transform aggregated counts and tags into simple properties
    const tagNames = client.tags?.map((t: { tag_name: string }) => t.tag_name) || [];

    return {
      ...client,
      documents_count: client.documents[0]?.count || 0,
      notes_count: client.notes[0]?.count || 0,
      tasks_count: client.tasks[0]?.count || 0,
      tags: tagNames,
    };
  }

  /**
   * Update client data
   *
   * Updates one or more fields of an existing client record.
   * Verifies user ownership before updating.
   *
   * @param id - The client ID to update
   * @param data - Partial client data to update
   * @param userId - The authenticated user's ID (required for authorization)
   * @returns Promise<Client | null> The updated client, or null if not found
   * @throws {Error} If database query fails
   */
  async updateClient(id: string, data: UpdateClientInput, userId: string): Promise<Client | null> {
    if (!userId) {
      throw new Error('User ID is required');
    }

    // Extract tags from data (they're not part of the clients table)
    const { tags, ...clientData } = data;

    const { data: client, error } = await this.supabase
      .from('clients')
      .update(clientData)
      .eq('id', id)
      .eq('assigned_to', userId)
      .eq('is_deleted', false)
      .select()
      .single();

    if (error) {
      // PGRST116 is PostgREST's "row not found" error
      if (error.code === 'PGRST116') {
        return null;
      }
      throw new Error(error.message);
    }

    // Handle tags if provided
    if (tags !== undefined && client) {
      // Delete existing tags
      await this.supabase
        .from('client_tags')
        .delete()
        .eq('client_id', id);

      // Add new tags if any
      if (tags.length > 0) {
        const tagRecords = tags.map((tagName: string) => ({
          client_id: client.id,
          tag_name: tagName,
          created_by: userId,
        }));

        const { error: tagError } = await this.supabase
          .from('client_tags')
          .insert(tagRecords);

        if (tagError) {
          // Log error but don't fail the request (tags are optional)
          console.error('Failed to update tags:', tagError);
        }
      }
    }

    return client;
  }

  /**
   * Soft delete a client
   *
   * Marks a client as deleted by setting is_deleted = true.
   * Verifies user ownership before deleting.
   *
   * @param id - The client ID to soft delete
   * @param userId - The authenticated user's ID (required for authorization)
   * @returns Promise<boolean> True if deletion succeeded
   * @throws {Error} If database query fails
   */
  async softDeleteClient(id: string, userId: string): Promise<boolean> {
    if (!userId) {
      throw new Error('User ID is required');
    }

    const { error } = await this.supabase
      .from('clients')
      .update({ is_deleted: true })
      .eq('id', id)
      .eq('assigned_to', userId)
      .eq('is_deleted', false);

    if (error) {
      throw new Error(error.message);
    }

    return true;
  }
}
